#![doc = include_str!("../README.md")]

use dis::prelude_ext::{alloc::*, core::*, proc_macro2_diagnostics::*};
use dis::{assert, Displayish, MacroDeepResult, MacroDiagnosticResult};

use proc_macro::TokenStream as ProcTokenStream;
use proc_macro2::{Literal, Span, TokenStream};
use proc_macro_rules::rules;

use quote::{quote_spanned, ToTokens, TokenStreamExt};
use std::sync::LazyLock;
use syn::{Expr, Ident, Path, Type};

mod file;

type MacroStreamResult = MacroDiagnosticResult<TokenStream>;

/// Thanks to build.rs.
const OUT_DIR: &str = env!("OUT_DIR");

static RND_PART: LazyLock<String> = LazyLock::new(|| {
    file::existing_rnd_part(OUT_DIR)
        .unwrap()
        .expect("Expecting a file generated by build.rs.")
});

fn ident(macro_crate: Path, given_name: Ident) -> Ident {
    let span = given_name.span();
    let macro_crate = macro_crate.into_token_stream().to_string();
    let macro_crate = macro_crate.replace(':', "_");

    let rnd_part = *RND_PART;
    let full_name = format!("{macro_crate}_private_{rnd_part}_given_name");
    Ident::new(&full_name, span)
}

#[proc_macro]
pub fn def_let(input: ProcTokenStream) -> ProcTokenStream {
    match def_let_impl(input.into()) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}

#[proc_macro]
pub fn def_mut(input: ProcTokenStream) -> ProcTokenStream {
    match def_mut_impl(input.into()) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}

#[proc_macro]
pub fn def_const(input: ProcTokenStream) -> ProcTokenStream {
    match def_const_impl(input.into()) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}

#[proc_macro]
pub fn use_let(input: ProcTokenStream) -> ProcTokenStream {
    match use_let_impl(input.into()) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}

#[proc_macro]
pub fn use_mut(input: ProcTokenStream) -> ProcTokenStream {
    match use_mut_impl(input.into()) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}

#[proc_macro]
pub fn use_const(input: ProcTokenStream) -> ProcTokenStream {
    match use_const_impl(input.into()) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}
// --------------

fn def_let_impl(input: TokenStream) -> MacroStreamResult {
    rules!(input => {
        ( $name:ident = $value:expr) => {
            let span = name.span();
            let _ = value;

            Ok(quote_spanned! {span=>

            })
        }
        ( $name:ident:$ty:ty = $value:expr) => {
            let span = name.span();
            Ok(quote_spanned! {span=>

            })
        }
    })
    .into()
}

fn def_let_impl_forwarder(input: TokenStream) -> MacroStreamResult {
    rules!(input => {
        ( $name:ident @ $path:path = $value:expr) => {
            let span = name.span();
            let _ = path;
            let _ = value;

            Ok(quote_spanned! {span=>

            })
        }
        ( $name:ident:$ty:ty = $value:expr) => {
            let span = name.span();
            let _ = ty;
            Ok(quote_spanned! {span=>

            })
        }
    })
    .into()
}
