#![doc = include_str!("../README.md")]

use dis::prelude_ext::{alloc::*, core::*, proc_macro2_diagnostics::*};
use dis::{Displayish, MacroDeepResult, MacroDiagnosticResult, MacroStreamResult, assert};

use proc_macro::TokenStream as ProcTokenStream;
use proc_macro_rules::rules;
use proc_macro2::{Literal, Span, TokenStream};

use quote::{ToTokens, TokenStreamExt, quote_spanned};
use std::str::FromStr;
use std::sync::LazyLock;
use syn::{Expr, Ident, Path, Type};

mod file;

/// Thanks to build.rs.
const OUT_DIR: &str = env!("OUT_DIR");

static RND_PART_LOWERCASE: LazyLock<String> = LazyLock::new(|| {
    file::existing_rnd_part(OUT_DIR)
        .unwrap()
        .expect("Expecting a file generated by build.rs.")
});
static RND_PART_UPPERCASE: LazyLock<String> = LazyLock::new(|| {
    let mut value = (*RND_PART_LOWERCASE).clone();
    value.make_ascii_uppercase();
    value
});

fn to_upper_lower_case(mut s: String, should_be_uppercase: bool) -> String {
    if s.is_ascii() {
        if should_be_uppercase {
            s.make_ascii_uppercase();
        } else {
            s.make_ascii_lowercase();
        }
    } else {
        // These create a new String - that's OK.
        s = if should_be_uppercase {
            s.to_uppercase()
        } else {
            s.to_lowercase()
        };
    };
    s
}

fn var_or_const_or_static_name(
    macro_crate_and_path: Option<&Path>,
    given_name: &Ident,
    should_be_uppercase: bool,
) -> Ident {
    let path_based_prefix = if let Some(macro_crate_and_path) = macro_crate_and_path {
        let mut path_based_prefix = macro_crate_and_path.into_token_stream().to_string();
        let path_based_prefix = to_upper_lower_case(path_based_prefix, should_be_uppercase);

        let mut path_based_prefix = path_based_prefix.replace("::", "_"); // this creates a new String - that's OK.
        path_based_prefix.push('_');
        Some(path_based_prefix)
    } else {
        None
    };
    let path_based_prefix = if let Some(path_based_prefix) = &path_based_prefix {
        path_based_prefix
    } else {
        ""
    };

    let private_ = if should_be_uppercase {
        "PRIVATE_"
    } else {
        "private_"
    };

    let span = given_name.span();
    let given_name = given_name.to_string();
    let given_name = to_upper_lower_case(given_name, should_be_uppercase);

    let rnd_part = if should_be_uppercase {
        &*RND_PART_UPPERCASE
    } else {
        &*RND_PART_LOWERCASE
    };

    // Intentionally putting the random part at the end, to make errors/warnings more
    // obvious/searchable.
    let full_name = format!("{path_based_prefix}{private_}{given_name}_{rnd_part}");

    Ident::new(&full_name, span)
}

#[proc_macro]
pub fn def_let(input: ProcTokenStream) -> ProcTokenStream {
    match def_let_grammar(input.into()) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}
/*
#[proc_macro]
pub fn def_mut(input: ProcTokenStream) -> ProcTokenStream {
    match def_mut_impl(input.into()) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}

#[proc_macro]
pub fn def_const(input: ProcTokenStream) -> ProcTokenStream {
    match def_const_impl(input.into()) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}

#[proc_macro]
pub fn use_let(input: ProcTokenStream) -> ProcTokenStream {
    match use_let_impl(input.into()) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}

#[proc_macro]
pub fn use_mut(input: ProcTokenStream) -> ProcTokenStream {
    match use_mut_impl(input.into()) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}

#[proc_macro]
pub fn use_const(input: ProcTokenStream) -> ProcTokenStream {
    match use_const_impl(input.into()) {
        Ok(output) => output.into(),
        Err(diag) => panic!("{:?}", diag), //diag.emit_as_expr_tokens().into(),
    }
}*/
// --------------

// @TODO generate code that
// 1. defines the let/mut/const
// 2. defines local (non-exported) macro_rules! local-variable-name-here
//    - BUT: if we do define (even just local) macro_rules! local-variable-name-here, then
//      - we definitely need to include $crate, to avoid conflicts; and
//      - worse: that consumer macro CANNOT be called multiple times in the same scope (conflicting
//        macro_rules!)
//      - without local macro_rules, that crate's macro(s) CAN be invoked multiple times in the same
//        scope, and any variables are shadowed.
//
// BUT: where/how do we include that consumer macro's $crate path? -> it would be HERE
//
//
// Either way: NOT for "re-entrant" macros. So we DON'T support macros usable like, or used like:
//
// custom_macro!( some-input-here... custom_macro!(...) ... )
//
// - unless the macro developer designed it so (that is, any expressions in the input would be
//   sub-scoped, like in a block {...}).
fn def_let_grammar(input: TokenStream) -> MacroStreamResult {
    use ConstStaticLetMut::LET;
    rules!(input => {
        ( $name:ident=$value:expr) => {
            def_const_static_let_mut(LET, &name, None, None, Some(&value))
        }
        ( $name:ident@$path:path=$value:expr ) => {
            def_const_static_let_mut(LET, &name, Some(&path), None, Some(&value))
        }

        ( $name:ident:$ty:ty = $value:expr ) => {
            def_const_static_let_mut(LET, &name, None, Some(&ty), Some(&value))
        }
        ( $name:ident@$path:path:$ty:ty = $value:expr ) => {
            def_const_static_let_mut(LET, &name, Some(&path), Some(&ty), Some(&value))
        }

        ( $name:ident ) => {
            def_const_static_let_mut(LET, &name, None, None, None)
        }
        ( $name:ident@$path:path) => {
            def_const_static_let_mut(LET, &name, Some(&path), None, None)
        }

        ( $name:ident:$ty:ty ) => {
            def_const_static_let_mut(LET, &name, None, Some(&ty), None)
        }
        ( $name:ident:@$path:path$ty:ty ) => {
            def_const_static_let_mut(LET, &name, Some(&path), Some(&ty), None)
        }
    })
    .into()
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum ConstStaticLetMut {
    CONST,
    STATIC,
    LET,
    MUT,
}
impl ConstStaticLetMut {
    /// One of: `let`, `let mut`, `const`, `static`.
    pub fn keywords(&self) -> &'static str {
        match self {
            Self::CONST => "const",
            Self::STATIC => "static",
            Self::LET => "let",
            Self::MUT => "let mut",
        }
    }
    pub fn should_be_uppercase(&self) -> bool {
        self == &Self::CONST || self == &Self::STATIC
    }
}

fn def_const_static_let_mut(
    which: ConstStaticLetMut,
    name: &Ident,
    path: Option<&Path>,
    ty: Option<&Type>,
    value: Option<&Expr>,
) -> MacroStreamResult {
    let var_name = var_or_const_or_static_name(path, name, which.should_be_uppercase());

    let span = name.span();

    let const_static_let_mut_part = TokenStream::from_str(which.keywords())
        .map_err_to()
        .map_macro_err()
        .span_err(span)?;

    let type_part = if let Some(ty) = ty {
        quote_spanned! {span=>
            : #ty
        }
    } else {
        TokenStream::new()
    };
    let assign_part = if let Some(value) = value {
        quote_spanned! {span=>
            = #value
        }
    } else {
        TokenStream::new()
    };
    Ok(quote_spanned! {span=>
        #const_static_let_mut_part #var_name #type_part #assign_part;
    })
}

fn def_let_impl_forwarder(input: TokenStream) -> MacroStreamResult {
    rules!(input => {
        ( $name:ident @ $path:path = $value:expr) => {
            let span = name.span();
            let _ = path;
            let _ = value;

            Ok(quote_spanned! {span=>

            })
        }
        ( $name:ident:$ty:ty = $value:expr) => {
            let span = name.span();
            let _ = ty;
            Ok(quote_spanned! {span=>

            })
        }
    })
    .into()
}
